save
git-svn-id: https://jff.googlecode.com/svn/trunk@558 1de5394f-e846-0410-8a38-9b14b2994ffe

diff --git a/dot_files/dot_bash_aliases b/dot_files/dot_bash_aliases
--- a/dot_files/dot_bash_aliases
+++ b/dot_files/dot_bash_aliases
@@ -22,3 +22,28 @@ alias ack=ack-grep
 
 alias locallib='eval $(perl -Mlocal::lib)'
 
+alias gb='git branch'
+alias gd='git diff'
+alias gdc='git diff --cached'
+alias gs='git status'
+alias gl='git log'
+alias gk='gitk --all'
+
+u () {
+    if expr "$1" : "[1-9][0-9]*$" >/dev/null; then
+        local arg="$1" s=..
+        while [ $((--arg)) -gt 0 ]; do
+            s="$s/.."
+        done
+        cd $s
+    else
+        local i=$(expr "$PWD" : ".*$1") j
+        if [ $i -gt 0 ]; then
+            j=$(expr index "$(expr substr "$PWD" $((++i)) 10000)" /)
+            [ $j -gt 0 ] && cd "$(expr substr "$PWD" 1 $((i+j)))"
+        else
+            echo "ERROR: can't find \"$1\" in \"$PWD\"!" >&2
+        fi
+    fi
+}
+
