* 用 ed 输出缓存的 find 输出，因为最后一行是 find 的返回值，sed 不支持 $-1 这样的行定位。
git-svn-id: https://jff.googlecode.com/svn/trunk@162 1de5394f-e846-0410-8a38-9b14b2994ffe

diff --git a/utils/find b/utils/find
--- a/utils/find
+++ b/utils/find
@@ -18,9 +18,8 @@
 #   2009-03-17  Liu Yubao
 #       * initial version
 #       * don't cache output of find if it goes wrong
-#
-# TODO:
-#   * how to cache return value of find command?
+#       * use ed instead of sed, suggested by Invader@newsmth
+#       * record return value, keep cache (conflict with second change above)
 #
 
 CACHE="$HOME/.find-cache"
@@ -33,9 +32,13 @@ file="$CACHE/$md5sum"
 [ -e "$CACHE" ] || mkdir -p "$CACHE"
 
 if [ -f "$file" ]; then
-    sed -ne '2,$p' "$file"
+    # The first line is cwd and args.
+    echo '2,$-1p' | ed -s "$file"
+    return `tail -1 "$file"`
 else
     echo "command: $cwd $args" > "$file"
-    { /usr/bin/find "$@" || rm "$file"; } | tee -a "$file"
+    # { /usr/bin/find "$@" || rm "$file"; } | tee -a "$file"
+    { /usr/bin/find "$@" ; retval=$?; } | tee -a "$file"
+    echo $retval >> "$file"
 fi
 
